# Numpy

Numpy is a foundation for pandas, so let's get into it.

In [1]:
import numpy as np

## Elemenetwise operations

In [4]:
data = np.random.normal(size=(2,3))
data

array([[-1.29716155,  0.91795317, -0.33185502],
       [ 0.47385421,  0.81647201, -1.70019896]])

In [5]:
data * 30

array([[-38.91484644,  27.53859518,  -9.95565068],
       [ 14.21562638,  24.49416035, -51.00596869]])

In [6]:
data + 3

array([[1.70283845, 3.91795317, 2.66814498],
       [3.47385421, 3.81647201, 1.29980104]])

In [8]:
data.dtype

dtype('float64')

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])